-- db/schema.sql
-- Oracle LMS DB 스키마 — NCS 직원 관리 시스템
-- DBeaver Oracle 드라이버에서 전체 선택 후 Alt+X 로 실행
-- 기존 객체가 있어도 DROP 후 재생성하므로 몇 번이든 실행 가능

-- ============================================================
-- 기존 테이블 DROP (FK 역순, 없으면 무시)
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TB_GRADING_RESULT CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TB_ASSIGNMENT_SUBMISSION CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TB_EDUCATION_HISTORY CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TB_EMPLOYEE CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================
-- 기존 시퀀스 DROP (없으면 무시)
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HISTORY_ID';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SUBMISSION_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RESULT_ID';     EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================
-- 시퀀스 생성
-- ============================================================
CREATE SEQUENCE SEQ_HISTORY_ID    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SUBMISSION_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESULT_ID     START WITH 1 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- TB_EMPLOYEE : 직원 기본정보
-- ============================================================
CREATE TABLE TB_EMPLOYEE (
    EMPLOYEE_ID  VARCHAR2(20)  NOT NULL,
    NAME         VARCHAR2(50)  NOT NULL,
    DEPARTMENT   VARCHAR2(100) NOT NULL,
    POSITION     VARCHAR2(50),
    JOIN_DATE    DATE          NOT NULL,
    EMAIL        VARCHAR2(100),
    CREATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_EMPLOYEE       PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT UQ_EMPLOYEE_EMAIL UNIQUE (EMAIL)
);

COMMENT ON TABLE  TB_EMPLOYEE             IS '직원 기본정보';
COMMENT ON COLUMN TB_EMPLOYEE.EMPLOYEE_ID IS '사번';
COMMENT ON COLUMN TB_EMPLOYEE.NAME        IS '이름';
COMMENT ON COLUMN TB_EMPLOYEE.DEPARTMENT  IS '부서';
COMMENT ON COLUMN TB_EMPLOYEE.POSITION    IS '직책';
COMMENT ON COLUMN TB_EMPLOYEE.JOIN_DATE   IS '입사일';
COMMENT ON COLUMN TB_EMPLOYEE.EMAIL       IS '이메일';

-- ============================================================
-- TB_EDUCATION_HISTORY : 교육 이수 내역
-- ============================================================
CREATE TABLE TB_EDUCATION_HISTORY (
    HISTORY_ID      NUMBER        NOT NULL,
    EMPLOYEE_ID     VARCHAR2(20)  NOT NULL,
    COURSE_NAME     VARCHAR2(200) NOT NULL,
    NCS_CODE        VARCHAR2(50),
    START_DATE      DATE,
    COMPLETION_DATE DATE,
    STATUS          VARCHAR2(20)  NOT NULL,
    SCORE           NUMBER(5,2),
    CREATED_AT      DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_EDUCATION_HISTORY PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_EDU_EMPLOYEE      FOREIGN KEY (EMPLOYEE_ID) REFERENCES TB_EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT CK_EDU_STATUS        CHECK (STATUS IN ('완료', '진행중', '미이수'))
);

COMMENT ON TABLE  TB_EDUCATION_HISTORY            IS '교육 이수 내역';
COMMENT ON COLUMN TB_EDUCATION_HISTORY.HISTORY_ID IS '이수 ID';
COMMENT ON COLUMN TB_EDUCATION_HISTORY.NCS_CODE   IS 'NCS 분류 코드';
COMMENT ON COLUMN TB_EDUCATION_HISTORY.STATUS     IS '완료/진행중/미이수';
COMMENT ON COLUMN TB_EDUCATION_HISTORY.SCORE      IS '이수 점수';

-- ============================================================
-- TB_ASSIGNMENT_SUBMISSION : 과제 제출 (CONTENT: 실제 과제 텍스트)
-- ============================================================
CREATE TABLE TB_ASSIGNMENT_SUBMISSION (
    SUBMISSION_ID   NUMBER        NOT NULL,
    EMPLOYEE_ID     VARCHAR2(20)  NOT NULL,
    COURSE_NAME     VARCHAR2(200) NOT NULL,
    ASSIGNMENT_NAME VARCHAR2(200) NOT NULL,
    SUBMIT_DATE     DATE,
    STATUS          VARCHAR2(20)  NOT NULL,
    CONTENT         CLOB,
    CREATED_AT      DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ASSIGNMENT_SUBMISSION PRIMARY KEY (SUBMISSION_ID),
    CONSTRAINT FK_SUBMIT_EMPLOYEE       FOREIGN KEY (EMPLOYEE_ID) REFERENCES TB_EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT CK_SUBMIT_STATUS         CHECK (STATUS IN ('제출', '미제출', '반려'))
);

COMMENT ON TABLE  TB_ASSIGNMENT_SUBMISSION               IS '과제 제출';
COMMENT ON COLUMN TB_ASSIGNMENT_SUBMISSION.SUBMISSION_ID IS '제출 ID';
COMMENT ON COLUMN TB_ASSIGNMENT_SUBMISSION.STATUS        IS '제출/미제출/반려';
COMMENT ON COLUMN TB_ASSIGNMENT_SUBMISSION.CONTENT       IS '과제 본문 텍스트';

-- ============================================================
-- TB_GRADING_RESULT : 채점 결과
-- ============================================================
CREATE TABLE TB_GRADING_RESULT (
    RESULT_ID     NUMBER        NOT NULL,
    SUBMISSION_ID NUMBER        NOT NULL,
    EMPLOYEE_ID   VARCHAR2(20)  NOT NULL,
    GRADER_ID     VARCHAR2(20)  NOT NULL,
    SCORE         NUMBER(5,2),
    PASS_YN       CHAR(1)       NOT NULL,
    FEEDBACK      VARCHAR2(4000),
    GRADED_DATE   DATE,
    CREATED_AT    DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_GRADING_RESULT   PRIMARY KEY (RESULT_ID),
    CONSTRAINT FK_GRADE_SUBMISSION FOREIGN KEY (SUBMISSION_ID) REFERENCES TB_ASSIGNMENT_SUBMISSION(SUBMISSION_ID),
    CONSTRAINT FK_GRADE_EMPLOYEE   FOREIGN KEY (EMPLOYEE_ID)   REFERENCES TB_EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT FK_GRADE_GRADER     FOREIGN KEY (GRADER_ID)     REFERENCES TB_EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT CK_PASS_YN          CHECK (PASS_YN IN ('Y', 'N'))
);

COMMENT ON TABLE  TB_GRADING_RESULT           IS '채점 결과';
COMMENT ON COLUMN TB_GRADING_RESULT.RESULT_ID IS '채점 ID';
COMMENT ON COLUMN TB_GRADING_RESULT.GRADER_ID IS '채점자 사번';
COMMENT ON COLUMN TB_GRADING_RESULT.PASS_YN   IS '합격 여부 Y/N';
COMMENT ON COLUMN TB_GRADING_RESULT.FEEDBACK  IS '채점 피드백';
